blank_issues_enabled: false
contact_links:
  - name: Node.js Hello World Documentation
    url: https://github.com/username/node-hello-world/blob/main/docs/README.md
    about: Please check our documentation before creating an issue
  - name: Node.js Documentation
    url: https://nodejs.org/en/docs/
    about: Official Node.js documentation for reference
  - name: Questions & Discussions
    url: https://github.com/username/node-hello-world/discussions
    about: Ask questions and discuss with other community members